import 'token.dart';
import 'expr.dart';

// -----------------------------------------------------------
// Warning! This code was generated by tools/generate_ast.dart
// -----------------------------------------------------------
    
abstract class StmtVisitor<R> {
  R visitExpressionStmt(Expression stmt);
  R visitPrintStmt(Print stmt);
  R visitVarStmt(Var stmt);
}

abstract class Stmt {
  R accept<R>(StmtVisitor<R> visitor);
}

class Expression extends Stmt {
  final Expr expression;

  Expression( this.expression);

  @override
  R accept<R>(StmtVisitor<R> visitor) {
    return visitor.visitExpressionStmt(this);
  }
}

class Print extends Stmt {
  final Expr expression;

  Print( this.expression);

  @override
  R accept<R>(StmtVisitor<R> visitor) {
    return visitor.visitPrintStmt(this);
  }
}

class Var extends Stmt {
  final Token name;
  final Expr? initializer;

  Var( this.name, this.initializer);

  @override
  R accept<R>(StmtVisitor<R> visitor) {
    return visitor.visitVarStmt(this);
  }
}
